title: humansconf
email: hello@humansconf.org
description: >- # this means to ignore newlines until "baseurl:"
  humansconf is a conference that aims to bring together people from all kinds of backgrounds and roles to discuss,
  share, and celebrate the stories and lessons learnt when humans come together to build impactful products.
  It takes place from 21-23 May 2020 at Seminarzentrum Rückersbach in Germany.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://humansconf.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: humansconf
github_username:  humansconf

plugins:
  - jekyll-feed

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
