title: humansconf
email: hello@humansconf.org
description: >-
  #humansconf is a community and event series centered around the most important thing when it comes to impactful technology products: People & their interactions!
baseurl: ""
url: "https://humansconf.org"
twitter_username: humansconf
github_username:  humansconf

plugins:
  - jekyll-feed

include:
  - _redirects

collections:
  events:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
